name: fra
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - pip:
      - albumentations==1.3.1
      - beautifulsoup4==4.12.2
      - charset-normalizer==3.4.2
      - dominate==2.8.0
      - idna==3.10
      - imageio==2.31.2
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - networkx==2.6.3
      - numpy==1.21.6
      - opencv-python-headless==4.11.0.86
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - qudida==0.0.4
      - requests==2.31.0
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - six==1.17.0
      - soupsieve==2.4.1
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu113
      - torchvision==0.13.1+cu113
      - tornado==6.2
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - visdom==0.2.4
      - websocket-client==1.6.1